; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = seeed_xiao_esp32s3
monitor_speed = 115200
upload_speed = 115200
build_flags = -std=gnu++17
lib_deps = bblanchon/ArduinoJson@^6.18.5
build_src_filter = +<*> -<.git/> -<.svn/>-<**/display.cpp>

[env:adafruit_esp32_s3_reverse_tft]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = adafruit_feather_esp32s3_reversetft
build_flags = -std=gnu++17 -DTFT_ENABLED -DBUTTONS_ENABLED
lib_deps = 
	bblanchon/ArduinoJson@^6.18.5
	adafruit/Adafruit ST7735 and ST7789 Library@^1.11.0
